version: '3.8'

services:
  django:
    build: .
    container_name: genomma_communication_center_django
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq-consumer
    environment:
      - ENVIRONMENT=development

  rabbitmq-consumer:
    build: .
    container_name: genomma_communication_center_consumer
    command: python ./rabbit/consumer.py  
    environment:
      - RABBIT_MQ_DEFAULT_QUEUE=genomma_communication_center_exchange
    networks:
      - default
    restart: unless-stopped

networks:
  default:
