# Generated by Django 5.0.2 on 2024-02-19 22:25

import core.freight.catalog
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Uuid')),
                ('freight_order', models.CharField(max_length=50, unique=True, verbose_name='Freight order')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], default=core.freight.catalog.FreightStatus['ACTIVE'], max_length=50, verbose_name='Status')),
                ('planned_km', models.FloatField(verbose_name='Planned km')),
                ('planned_time', models.BigIntegerField(verbose_name='Planned time')),
                ('vehicle_resource', models.CharField(max_length=50, verbose_name='Vehicle resource')),
                ('plate_number', models.CharField(max_length=50, verbose_name='Plate number')),
                ('carrier', models.CharField(max_length=50, verbose_name='Carrier')),
                ('driver', models.CharField(max_length=50, verbose_name='Driver')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Freight',
                'verbose_name_plural': 'Freights',
                'db_table': 'freight',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Uuid')),
                ('evento', models.CharField(max_length=50, verbose_name='Event')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('sequence', models.CharField(max_length=10, verbose_name='Sequence')),
                ('planned_date', models.CharField(max_length=150, verbose_name='Planned date')),
                ('planned_hour', models.CharField(max_length=150, verbose_name='Planned hour')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='freight.freight')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreightTransaction',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('process_status', models.IntegerField(choices=[(0, 'Pendiente de procesar'), (1, 'Procesado'), (2, 'Procesado correctamente'), (3, 'Procesado con errores'), (4, 'En error')], default=0, verbose_name='Process status')),
                ('mzone_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mzone code')),
                ('mzone_message', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mzone message')),
                ('broker_message', models.CharField(blank=True, max_length=150, null=True, verbose_name='Broker message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='freight.freight')),
            ],
            options={
                'verbose_name': 'Freight transaction',
                'verbose_name_plural': 'Freight transactions',
                'db_table': 'freight_transaction',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Uuid')),
                ('stage_id', models.CharField(max_length=50, verbose_name='Stage id')),
                ('origen', models.CharField(max_length=50, verbose_name='Origin')),
                ('destino', models.CharField(max_length=50, verbose_name='Destination')),
                ('plate_number', models.CharField(max_length=50, verbose_name='Plate number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='freight.freight')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'db_table': 'stage',
                'ordering': ['created_at'],
            },
        ),
    ]
