# Generated by Django 5.0.2 on 2024-02-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0002_rename_event_event_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_id',
            field=models.CharField(max_length=50, verbose_name='Stage id'),
        ),
    ]
