# Generated by Django 5.0.2 on 2024-02-09 18:57

import core.freight.catalog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_alter_stage_stage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], default=core.freight.catalog.FreightStatus['ACTIVE'], max_length=50, verbose_name='Status'),
        ),
    ]
