# Generated by Django 5.0.2 on 2024-02-12 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0004_alter_freight_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['created_at'], 'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
        migrations.CreateModel(
            name='FreightTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Uuid')),
                ('process_status', models.IntegerField(choices=[(0, 'Pendiente de procesar'), (1, 'Procesado'), (2, 'Procesado correctamente'), (3, 'Procesado con errores'), (4, 'En error')], default=0, verbose_name='Process status')),
                ('mzone_code', models.CharField(max_length=50, verbose_name='Mzone code')),
                ('mzone_message', models.CharField(max_length=150, verbose_name='Mzone message')),
                ('broker_message', models.CharField(max_length=150, verbose_name='Broker message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='freight.freight')),
            ],
            options={
                'verbose_name': 'Freight transaction',
                'verbose_name_plural': 'Freight transactions',
                'db_table': 'freight_transaction',
                'ordering': ['created_at'],
            },
        ),
    ]
