# Generated by Django 5.0.2 on 2024-02-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0006_alter_freighttransaction_broker_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freight',
            name='transaction_id',
        ),
    ]
